version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
